// <auto-generated />
namespace ErrorLoggerModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class appStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201705061716058_appStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
